
services:
  backend:
    build: .\socialmedia\
    container_name: socailmedia-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

      # MOm2Jl7ggZB80nZK db pasword

  frontend:
    build: .\socialmedia-frontend\
    container_name: socialmedia-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
